export const carsCollection = [{
    'id': 1,
    'car': 'Oldsmobile',
    'carModel': 'Cutlass Supreme',
    'carYear': 1995,
    'gender': 'Male',
    'city': 'Minneapolis',
    'state': 'Minnesota'
}, {
    'id': 2,
    'car': 'Porsche',
    'carModel': '911',
    'carYear': 2005,
    'gender': 'Female',
    'city': 'Springfield',
    'state': 'Missouri'
}, {
    'id': 3,
    'car': 'Hyundai',
    'carModel': 'Accent',
    'carYear': 2004,
    'gender': 'Female',
    'city': 'Portland',
    'state': 'Oregon' 
}, {
    'id': 4,
    'car': 'Ford',
    'carModel': 'F-Series',
    'carYear': 1994,
    'gender': 'Male',
    'city': 'Pittsburgh',
    'state': 'Pennsylvania'
}, {
    'id': 5,
    'car': 'Audi',
    'carModel': 'A8',
    'carYear': 2002,
    'gender': 'Female',
    'city': 'Jackson',
    'state': 'Mississippi'
}, {
    'id': 6,
    'car': 'Mercury',
    'carModel': 'Tracer',
    'carYear': 1992,
    'gender': 'Male',
    'city': 'Vancouver',
    'state': 'Washington'
}, {
    'id': 7,
    'car': 'Ford',
    'carModel': 'F150',
    'carYear': 1993,
    'gender': 'Female',
    'city': 'Shreveport',
    'state': 'Louisiana'
}, {
    'id': 8,
    'car': 'Daihatsu',
    'carModel': 'Charade',
    'carYear': 1992,
    'gender': 'Male',
    'city': 'Saint Louis',
    'state': 'Missouri'
}, {
    'id': 9,
    'car': 'Audi',
    'carModel': 'Coupe GT',
    'carYear': 1987,
    'gender': 'Male',
    'city': 'Sacramento',
    'state': 'California'
}, {
    'id': 10,
    'car': 'GMC',
    'carModel': '1500',
    'carYear': 1998,
    'gender': 'Female',
    'city': 'Cambridge',
    'state': 'Massachusetts'
}, {
    'id': 11,
    'car': 'Mercury',
    'carModel': 'Cougar',
    'carYear': 1967,
    'gender': 'Female',
    'city': 'San Francisco',
    'state': 'California'
}, {
    'id': 12,
    'car': 'Jeep',
    'carModel': 'Compass',
    'carYear': 2010,
    'gender': 'Male',
    'city': 'Saint Paul',
    'state': 'Minnesota'
}, {
    'id': 13,
    'car': 'Ford',
    'carModel': 'E-Series',
    'carYear': 2012,
    'gender': 'Female',
    'city': 'Atlanta',
    'state': 'Georgia'
}, {
    'id': 14,
    'car': 'Cadillac',
    'carModel': 'Escalade EXT',
    'carYear': 2009,
    'gender': 'Male',
    'city': 'Gainesville',
    'state': 'Florida'
}, {
    'id': 15,
    'car': 'Suzuki',
    'carModel': 'XL-7',
    'carYear': 2003,
    'gender': 'Male',
    'city': 'Arlington',
    'state': 'Virginia'
}, {
    'id': 16,
    'car': 'Infiniti',
    'carModel': 'Q',
    'carYear': 2002,
    'gender': 'Male',
    'city': 'Memphis',
    'state': 'Tennessee'
}, {
    'id': 17,
    'car': 'Dodge',
    'carModel': 'Grand Caravan',
    'carYear': 2011,
    'gender': 'Male',
    'city': 'Fresno',
    'state': 'California'
}, {
    'id': 18,
    'car': 'BMW',
    'carModel': '3 Series',
    'carYear': 2009,
    'gender': 'Female',
    'city': 'Iowa City',
    'state': 'Iowa'
}, {
    'id': 19,
    'car': 'Chevrolet',
    'carModel': 'Suburban 2500',
    'carYear': 1992,
    'gender': 'Male',
    'city': 'Philadelphia',
    'state': 'Pennsylvania'
}, {
    'id': 20,
    'car': 'Hyundai',
    'carModel': 'Elantra',
    'carYear': 2013,
    'gender': 'Male',
    'city': 'Miami',
    'state': 'Florida'
}, {
    'id': 21,
    'car': 'Aston Martin',
    'carModel': 'V12 Vantage',
    'carYear': 2011,
    'gender': 'Male',
    'city': 'Salt Lake City',
    'state': 'Utah'
}, {
    'id': 22,
    'car': 'Volvo',
    'carModel': 'S40',
    'carYear': 2011,
    'gender': 'Female',
    'city': 'Phoenix',
    'state': 'Arizona'
}, {
    'id': 23,
    'car': 'Mercedes-Benz',
    'carModel': 'E-Class',
    'carYear': 2000,
    'gender': 'Female',
    'city': 'Amarillo',
    'state': 'Texas'
}, {
    'id': 24,
    'car': 'Cadillac',
    'carModel': 'Escalade',
    'carYear': 2002,
    'gender': 'Female',
    'city': 'Billings',
    'state': 'Montana'
}, {
    'id': 25,
    'car': 'Lexus',
    'carModel': 'SC',
    'carYear': 1995,
    'gender': 'Female',
    'city': 'Lynchburg',
    'state': 'Virginia'
}, {
    'id': 26,
    'car': 'Chevrolet',
    'carModel': 'Blazer',
    'carYear': 1999,
    'gender': 'Female',
    'city': 'Baltimore',
    'state': 'Maryland'
}, {
    'id': 27,
    'car': 'Audi',
    'carModel': '4000s Quattro',
    'carYear': 1986,
    'gender': 'Male',
    'city': 'Visalia',
    'state': 'California'
}, {
    'id': 28,
    'car': 'Mercury',
    'carModel': 'Grand Marquis',
    'carYear': 2005,
    'gender': 'Male',
    'city': 'Lubbock',
    'state': 'Texas'
}, {
    'id': 29,
    'car': 'Maserati',
    'carModel': 'Spyder',
    'carYear': 1990,
    'gender': 'Female',
    'city': 'Hattiesburg',
    'state': 'Mississippi'
}, {
    'id': 30,
    'car': 'Kia',
    'carModel': 'Sportage',
    'carYear': 2011,
    'gender': 'Female',
    'city': 'Boston',
    'state': 'Massachusetts'
}, {
    'id': 31,
    'car': 'Peugeot',
    'carModel': '207',
    'carYear': 2006,
    'gender': 'Male',
    'city': 'Abilene',
    'state': 'Texas'
}, {
    'id': 32,
    'car': 'Volvo',
    'carModel': 'XC70',
    'carYear': 2012,
    'gender': 'Female',
    'city': 'Monticello',
    'state': 'Minnesota'
}, {
    'id': 33,
    'car': 'Subaru',
    'carModel': 'Tribeca',
    'carYear': 2006,
    'gender': 'Male',
    'city': 'Fresno',
    'state': 'California'
}, {
    'id': 34,
    'car': 'Kia',
    'carModel': 'Amanti',
    'carYear': 2008,
    'gender': 'Male',
    'city': 'Dallas',
    'state': 'Texas'
}, {
    'id': 35,
    'car': 'Hyundai',
    'carModel': 'Tucson',
    'carYear': 2008,
    'gender': 'Female',
    'city': 'Seattle',
    'state': 'Washington'
}, {
    'id': 36,
    'car': 'Mitsubishi',
    'carModel': '3000GT',
    'carYear': 1997,
    'gender': 'Female',
    'city': 'Canton',
    'state': 'Ohio'
}, {
    'id': 37,
    'car': 'Dodge',
    'carModel': 'Ram Van 3500',
    'carYear': 2001,
    'gender': 'Female',
    'city': 'San Francisco',
    'state': 'California'
}, {
    'id': 38,
    'car': 'Lexus',
    'carModel': 'LFA',
    'carYear': 2012,
    'gender': 'Male',
    'city': 'Cleveland',
    'state': 'Ohio'
}, {
    'id': 39,
    'car': 'Saab',
    'carModel': '900',
    'carYear': 1998,
    'gender': 'Female',
    'city': 'Philadelphia',
    'state': 'Pennsylvania'
}, {
    'id': 40,
    'car': 'Cadillac',
    'carModel': 'Eldorado',
    'carYear': 1996,
    'gender': 'Male',
    'city': 'Honolulu',
    'state': 'Hawaii'
}] 